name: "Make README.md and index.json"
description: "Run python script which makes README.md and index.json"
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install glob2
        pip install tqdm
        pip install nbformat
      shell: bash
    - name: Make README.md and index.json
      working-directory: ./notebook_examples
      id: make_readme
      run: python make_readme.py
      shell: bash
