name: "Commit changes"
description: "Commits changes"

inputs:
  commit_message:
    description: Commit message
    required: false
    default: Auto commit changes
  commit_author:
    description: Value used for the commit author. Defaults to the github-actions[bot].
    required: false
    default: "github-actions[bot]"
  commit_user_email:
    description: Email address used for the commit user. Defaults to the 'github-actions[bot]@users.noreply.github.com'
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  file_pattern:
    description: File pattern used for `git add`. For example `src/*.js`
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    # NOTE: git commit -m '${{ inputs.commit_message }}' || echo "No changes to commit"
    # needs the part after OR operator: '|| echo "No changes to commit'
    # to catch the error if there are no changes to commit
    - name: Commit
      id: commit_changes
      run: |
        git config user.email "you@example.com"
        git config user.name ${{ github.actor }}
        git add '${{ inputs.file_pattern }}'
        echo "COMMIT_RESULT=green" >> $GITHUB_OUTPUT
        git commit -m '${{ inputs.commit_message }}' || echo "COMMIT_RESULT=red" >> $GITHUB_OUTPUT
      shell: bash
    - name: Check output
      run: |
        echo "The commit result is ${{ steps.commit_changes.outputs.COMMIT_RESULT }}"
      shell: bash
    - name: Push and pull-request
      run: |
        git push
        hub pull-request
      shell: bash
