name: "Commit, push and create pull-request"
description: "Commit, push and create pull-request if there are changes"

inputs:
  branch_name: 
    description: A branch name
    required: true
  commit_message:
    description: Commit message
    required: false
    default: Auto commit changes
  commit_author:
    description: Value used for the commit author. Defaults to the github-actions[bot].
    required: false
    default: "github-actions[bot]"
  commit_user_email:
    description: Email address used for the commit user. Defaults to the 'github-actions[bot]@users.noreply.github.com'
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  file_pattern:
    description: File pattern used for `git add`. For example `src/*.js`
    required: false
    default: "."


runs:
  using: "composite"
  steps:
    - name: Setting git user
      run: |
        echo "Setting git user to ${{ github.actor }}"
        git config user.email "you@example.com"
        git config user.name ${{ github.actor }}
      shell: bash
    - name: Staging changes
      id: staging_changes
      run: |
        echo "Staging changes matching the pattern ${{ inputs.file_pattern }} if such exist."
        git add '${{ inputs.file_pattern }}'
        CHANGED_FILES=$(git diff --cached --name-only)
        if [[ -z $CHANGED_FILES ]]; then
          echo "There are no changes to stage."
          echo "CHANGED_FILES=false" >> $GITHUB_OUTPUT
        else 
          echo "Following files changes has been staged:"
          echo "$CHANGED_FILES"
          echo "CHANGED_FILES=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Commit, push and create pull-request
      if: steps.staging_changes.outputs.CHANGED_FILES == 'true'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Commiting, pushing and creating a PR"
        git checkout -b ${{ inputs.branch_name }}'
        git commit -m '${{ inputs.commit_message }}'
        git push
        gh pr create --title "README.md auto update" --body "README.md has been auto updated by GitHub action"
      shell: bash
